from typing import Union

has_integer_precision: bool

class cost_type:
    def __init__(self, value: Union[int, float]) -> None: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...

class distance_type:
    def __init__(self, value: Union[int, float]) -> None: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...

class duration_type:
    def __init__(self, value: Union[int, float]) -> None: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
