PRECISION: str

def equal_float(a: float, b: float, tol: float = ...) -> bool: ...
def equal_int(a: int, b: int, tol: float = ...) -> bool: ...
def smaller_float(a: float, b: float, tol: float = ...) -> bool: ...
def smaller_int(a: int, b: int, tol: float = ...) -> bool: ...
def greater_float(a: float, b: float, tol: float = ...) -> bool: ...
def greater_int(a: int, b: int, tol: float = ...) -> bool: ...
