from enum import Enum
from typing import Iterator, Sequence, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

_BUILD_TYPE: str

class ActivityType(Enum):
    CLIENT = 0
    DEPOT = 1
    PICKUP = 2
    DELIVERY = 3

class Activity:
    @overload
    def __init__(self, type: ActivityType, idx: int) -> None: ...
    @overload
    def __init__(self, description: str) -> None: ...
    @property
    def type(self) -> ActivityType: ...
    @property
    def idx(self) -> int: ...
    def is_client(self) -> bool: ...
    def is_depot(self) -> bool: ...
    def is_shipment(self) -> bool: ...
    def is_pickup(self) -> bool: ...
    def is_delivery(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class CostEvaluator:
    def __init__(
        self,
        load_penalties: Sequence[float],
        tw_penalty: float,
        dist_penalty: float,
    ) -> None: ...
    def load_penalty(
        self, load: float, capacity: float, dimension: int
    ) -> float: ...
    def tw_penalty(self, time_warp: float) -> float: ...
    def dist_penalty(self, distance: float, max_distance: float) -> float: ...
    def penalised_cost(self, solution: Solution) -> float: ...
    def cost(self, solution: Solution) -> float: ...

class DynamicBitset:
    def __init__(self, num_bits: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, idx: int) -> bool: ...
    def __setitem__(self, idx: int, value: bool) -> None: ...
    def all(self) -> bool: ...
    def any(self) -> bool: ...
    def none(self) -> bool: ...
    def count(self) -> int: ...
    def __len__(self) -> int: ...
    def __or__(self, other: DynamicBitset) -> DynamicBitset: ...
    def __and__(self, other: DynamicBitset) -> DynamicBitset: ...
    def __xor__(self, other: DynamicBitset) -> DynamicBitset: ...
    def __invert__(self) -> DynamicBitset: ...
    def set(self) -> DynamicBitset: ...
    def reset(self) -> DynamicBitset: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class PiecewiseLinearFunction:
    @overload
    def __init__(
        self,
        points: Sequence[tuple[float, float]],
    ) -> None: ...
    @overload
    def __init__(
        self,
        breakpoints: Sequence[float],
        segments: Sequence[tuple[float, float]],
    ) -> None: ...
    def __call__(self, x: float) -> float: ...
    @property
    def breakpoints(self) -> list[float]: ...
    @property
    def segments(self) -> list[tuple[float, float]]: ...
    def is_monotonically_increasing(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Location:
    x: float
    y: float
    name: str
    def __init__(self, x: float, y: float, *, name: str = "") -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Client:
    location: int
    delivery: list[float]
    pickup: list[float]
    service_duration: float
    tw_early: float
    tw_late: float
    release_time: float
    prize: float
    required: bool
    group: int | None
    name: str
    def __init__(
        self,
        location: int,
        delivery: Sequence[float] = [],
        pickup: Sequence[float] = [],
        service_duration: float = 0,
        tw_early: float = 0,
        tw_late: float = ...,
        release_time: float = 0,
        prize: float = 0,
        required: bool = True,
        group: int | None = None,
        *,
        name: str = "",
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class ClientGroup:
    required: bool
    mutually_exclusive: bool
    name: str
    def __init__(
        self,
        clients: list[int] = [],
        required: bool = True,
        *,
        name: str = "",
    ) -> None: ...
    @property
    def clients(self) -> list[int]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def add_client(self, client: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Depot:
    location: int
    tw_early: float
    tw_late: float
    service_duration: float
    name: str
    def __init__(
        self,
        location: int,
        tw_early: float = 0,
        tw_late: float = ...,
        service_duration: float = 0,
        *,
        name: str = "",
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class ShipmentStep:
    location: int
    tw_early: float
    tw_late: float
    service_duration: float
    def __init__(
        self,
        location: int,
        tw_early: float = 0,
        tw_late: float = ...,
        service_duration: float = 0,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Shipment:
    pickup: ShipmentStep
    delivery: ShipmentStep
    amount: list[float]
    prize: float
    required: bool
    name: str
    def __init__(
        self,
        pickup_location: int,
        delivery_location: int,
        pickup_tw_early: float = 0,
        pickup_tw_late: float = ...,
        pickup_service_duration: float = 0,
        delivery_tw_early: float = 0,
        delivery_tw_late: float = ...,
        delivery_service_duration: float = 0,
        amount: Sequence[float] = [],
        prize: float = 0,
        required: bool = True,
        *,
        name: str = "",
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class VehicleType:
    num_available: int
    start_depot: int
    end_depot: int
    capacity: list[float]
    tw_early: float
    tw_late: float
    shift_duration: float
    max_distance: float
    fixed_cost: float
    unit_distance_cost: float
    unit_duration_cost: float
    profile: int
    start_late: float
    initial_load: list[float]
    reload_depots: list[int]
    max_reloads: int
    max_overtime: float
    unit_overtime_cost: float
    max_duration: float
    name: str
    def __init__(
        self,
        num_available: int = 1,
        capacity: Sequence[float] = [],
        start_depot: int = 0,
        end_depot: int = 0,
        fixed_cost: float = 0,
        tw_early: float = 0,
        tw_late: float = ...,
        shift_duration: float = ...,
        max_distance: float = ...,
        unit_distance_cost: float = 1,
        unit_duration_cost: float = 0,
        profile: int = 0,
        start_late: float | None = None,
        initial_load: Sequence[float] = [],
        reload_depots: list[int] = [],
        max_reloads: int = ...,
        max_overtime: float = 0,
        unit_overtime_cost: float = 0,
        *,
        name: str = "",
    ) -> None: ...
    @property
    def max_trips(self) -> int: ...
    def replace(
        self,
        num_available: int | None = None,
        capacity: Sequence[float] | None = None,
        start_depot: int | None = None,
        end_depot: int | None = None,
        fixed_cost: float | None = None,
        tw_early: float | None = None,
        tw_late: float | None = None,
        shift_duration: float | None = None,
        max_distance: float | None = None,
        unit_distance_cost: float | None = None,
        unit_duration_cost: float | None = None,
        profile: int | None = None,
        start_late: float | None = None,
        initial_load: Sequence[float] | None = None,
        reload_depots: list[int] | None = None,
        max_reloads: int | None = None,
        max_overtime: float | None = None,
        unit_overtime_cost: float | None = None,
        *,
        name: str | None = None,
    ) -> VehicleType: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class ProblemData:
    def __init__(
        self,
        locations: list[Location],
        clients: list[Client],
        depots: list[Depot],
        vehicle_types: list[VehicleType],
        distance_matrices: Sequence[ArrayLike],
        duration_matrices: Sequence[ArrayLike],
        groups: list[ClientGroup] = [],
        shipments: list[Shipment] = [],
    ) -> None: ...
    def locations(self) -> list[Location]: ...
    def clients(self) -> list[Client]: ...
    def depots(self) -> list[Depot]: ...
    def groups(self) -> list[ClientGroup]: ...
    def shipments(self) -> list[Shipment]: ...
    def vehicle_types(self) -> list[VehicleType]: ...
    def distance_matrices(self) -> list[NDArray[np.float64]]: ...
    def duration_matrices(self) -> list[NDArray[np.float64]]: ...
    def replace(
        self,
        locations: list[Location] | None = None,
        clients: list[Client] | None = None,
        depots: list[Depot] | None = None,
        vehicle_types: list[VehicleType] | None = None,
        distance_matrices: Sequence[ArrayLike] | None = None,
        duration_matrices: Sequence[ArrayLike] | None = None,
        groups: list[ClientGroup] | None = None,
        shipments: list[Shipment] | None = None,
    ) -> ProblemData: ...
    def location(self, location: int) -> Location: ...
    def client(self, client: int) -> Client: ...
    def depot(self, depot: int) -> Depot: ...
    def group(self, group: int) -> ClientGroup: ...
    def shipment(self, shipment: int) -> Shipment: ...
    def vehicle_type(self, vehicle_type: int) -> VehicleType: ...
    def distance_matrix(self, profile: int) -> NDArray[np.float64]: ...
    def duration_matrix(self, profile: int) -> NDArray[np.float64]: ...
    def has_time_windows(self) -> bool: ...
    @property
    def num_clients(self) -> int: ...
    @property
    def num_groups(self) -> int: ...
    @property
    def num_shipments(self) -> int: ...
    @property
    def num_depots(self) -> int: ...
    @property
    def num_locations(self) -> int: ...
    @property
    def num_vehicles(self) -> int: ...
    @property
    def num_vehicle_types(self) -> int: ...
    @property
    def num_profiles(self) -> int: ...
    @property
    def num_load_dimensions(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class ScheduledActivity(Activity):
    @property
    def trip(self) -> int: ...
    @property
    def start_time(self) -> float: ...
    @property
    def end_time(self) -> float: ...
    @property
    def duration(self) -> float: ...
    @property
    def wait_duration(self) -> float: ...
    @property
    def time_warp(self) -> float: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Route:
    @overload
    def __init__(
        self,
        data: ProblemData,
        activities: list[Activity],
        vehicle_type: int,
    ) -> None: ...
    @overload
    def __init__(
        self,
        data: ProblemData,
        visits: list[int],
        vehicle_type: int,
    ) -> None: ...
    def __getitem__(self, idx: int) -> ScheduledActivity: ...
    def __iter__(self) -> Iterator[ScheduledActivity]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def is_feasible(self) -> bool: ...
    def has_excess_load(self) -> bool: ...
    def has_excess_distance(self) -> bool: ...
    def has_time_warp(self) -> bool: ...
    def delivery(self) -> list[float]: ...
    def pickup(self) -> list[float]: ...
    def excess_load(self) -> list[float]: ...
    def excess_distance(self) -> float: ...
    def fixed_vehicle_cost(self) -> float: ...
    def distance(self) -> float: ...
    def distance_cost(self) -> float: ...
    def duration(self) -> float: ...
    def overtime(self) -> float: ...
    def duration_cost(self) -> float: ...
    def num_clients(self) -> int: ...
    def num_shipments(self) -> int: ...
    def num_depots(self) -> int: ...
    def num_trips(self) -> int: ...
    def time_warp(self) -> float: ...
    def start_time(self) -> float: ...
    def end_time(self) -> float: ...
    def slack(self) -> float: ...
    def service_duration(self) -> float: ...
    def travel_duration(self) -> float: ...
    def wait_duration(self) -> float: ...
    def release_time(self) -> float: ...
    def prizes(self) -> float: ...
    def vehicle_type(self) -> int: ...
    def start_depot(self) -> int: ...
    def end_depot(self) -> int: ...
    def schedule(self) -> list[ScheduledActivity]: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class Solution:
    def __init__(
        self,
        data: ProblemData,
        routes: list[Route] | list[list[int]],
    ) -> None: ...
    @classmethod
    def make_random(
        cls, data: ProblemData, rng: RandomNumberGenerator
    ) -> Solution: ...
    def routes(self) -> list[Route]: ...
    def unplanned(self) -> list[Activity]: ...
    def has_excess_load(self) -> bool: ...
    def has_excess_distance(self) -> bool: ...
    def has_time_warp(self) -> bool: ...
    def distance(self) -> float: ...
    def distance_cost(self) -> float: ...
    def duration(self) -> float: ...
    def overtime(self) -> float: ...
    def duration_cost(self) -> float: ...
    def excess_load(self) -> list[float]: ...
    def excess_distance(self) -> float: ...
    def fixed_vehicle_cost(self) -> float: ...
    def time_warp(self) -> float: ...
    def prizes(self) -> float: ...
    def uncollected_prizes(self) -> float: ...
    def is_feasible(self) -> bool: ...
    def is_complete(self) -> bool: ...
    def num_routes(self) -> int: ...
    def num_trips(self) -> int: ...
    def num_clients(self) -> int: ...
    def num_shipments(self) -> int: ...
    def num_missing_clients(self) -> int: ...
    def num_missing_groups(self) -> int: ...
    def num_missing_shipments(self) -> int: ...
    def __copy__(self) -> Solution: ...
    def __deepcopy__(self, memo: dict) -> Solution: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> tuple: ...
    def __setstate__(self, state: tuple, /) -> None: ...

class LoadSegment:
    def __init__(
        self,
        initial: float,
        delta: float,
        increase: float,
        excess_load: float = 0,
    ) -> None: ...
    @staticmethod
    def merge(first: LoadSegment, second: LoadSegment) -> LoadSegment: ...
    def initial(self) -> float: ...
    def delta(self) -> float: ...
    def increase(self) -> float: ...
    def load(self) -> float: ...
    def excess_load(self, capacity: float) -> float: ...
    def finalise(self, capacity: float) -> LoadSegment: ...

class DurationSegment:
    def __init__(
        self,
        duration: float = 0,
        time_warp: float = 0,
        start_early: float = 0,
        start_late: float = ...,
        release_time: float = 0,
        cum_duration: float = 0,
        cum_time_warp: float = 0,
        prev_end_late: float = ...,
    ) -> None: ...
    @staticmethod
    def merge(
        edge_duration: float,
        first: DurationSegment,
        second: DurationSegment,
    ) -> DurationSegment: ...
    def duration(self) -> float: ...
    def end_early(self) -> float: ...
    def end_late(self) -> float: ...
    def finalise_back(self) -> DurationSegment: ...
    def finalise_front(self) -> DurationSegment: ...
    def prev_end_late(self) -> float: ...
    def release_time(self) -> float: ...
    def slack(self) -> float: ...
    def start_early(self) -> float: ...
    def start_late(self) -> float: ...
    def time_warp(self, max_duration: float = ...) -> float: ...

class RandomNumberGenerator:
    @overload
    def __init__(self, seed: int) -> None: ...
    @overload
    def __init__(self, state: list[int]) -> None: ...
    @staticmethod
    def max() -> int: ...
    @staticmethod
    def min() -> int: ...
    def rand(self) -> float: ...
    def randint(self, high: int) -> int: ...
    def __call__(self) -> int: ...
    def state(self) -> list[int]: ...
