class XorShift128:
    def __init__(self, seed: int) -> None: ...
    def max(self) -> int: ...
    def min(self) -> int: ...
    def rand(self) -> float: ...
    def randint(self, high: int) -> int: ...
    def __call__(self) -> int: ...
