labels: [question]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for your interest in PyVRP!
        This form asks a few questions up front because answering user questions and solving problems on GitHub consumes a significant amount of our time.
        By answering these questions in a structured way through this form, it will be much easier to help you.

        Before posting about your question or error, please make sure to check our [FAQ](https://pyvrp.org/setup/faq.html), [discussions](https://github.com/PyVRP/PyVRP/discussions?discussions_q=) and [issue tracker](https://github.com/PyVRP/PyVRP/issues?q=is%3Aissue) for similar posts.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        What is the problem, question, or error?
        Please explain what you are currently doing, what you expect to happen, and what is actually happening.

        Is your problem related to a specific data instance?
        Then please include a pickle file of your [`ProblemData`](https://pyvrp.org/api/pyvrp.html#pyvrp._pyvrp.ProblemData) instance here.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example code
      description: >
        If your discussion relates to a non-functional code example, please add it here.
        Make sure it is a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example).
        If we can copy and run it and replicate the issue right away, there is a much higher chance we will be able to help you.
      placeholder: |
        from pyvrp import Model

        m = Model()
        ...
      render: python
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which operating system(s) do you use?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
    validations:
      required: true
  - type: textarea
    id: pyvrp-version
    attributes:
      label: PyVRP and dependency versions
      description: |
        Which versions of PyVRP and its dependencies are you using? You can obtain these using:
        ```bash
        python -c "import pyvrp; pyvrp.show_versions()"
        ```
        Please add the output here.
      render: bash
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any additional information that you think may be useful.
