from pyvrp import ProblemData

class NodeOperator:
    def __init__(self, *args, **kwargs) -> None: ...

class Exchange10(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange11(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange20(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange21(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange22(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange30(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange31(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange32(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...

class Exchange33(NodeOperator):
    def __init__(self, data: ProblemData) -> None: ...
