from typing import List

from pyvrp import Individual, PenaltyManager, ProblemData, XorShift128

Neighbours = List[List[int]]

class LocalSearch:
    def __init__(
        self,
        data: ProblemData,
        penalty_manager: PenaltyManager,
        rng: XorShift128,
        neighbours: Neighbours,
    ) -> None: ...
    def add_node_operator(self, op) -> None: ...
    def add_route_operator(self, op) -> None: ...
    def set_neighbours(self, neighbours: Neighbours) -> None: ...
    def get_neighbours(self) -> Neighbours: ...
    def intensify(
        self, individual: Individual, overlapToleranceDegrees: int = 0
    ) -> None: ...
    def search(self, individual: Individual) -> None: ...
