name: CodSpeed

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  bench:
    name: Run benchmarks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version: "0.11.3"
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --no-install-project
      - name: Update package index
        run: |
          # Change mirror priorities because Azure can be really slow - https://github.com/actions/runner-images/issues/7048.
          sudo sed -i '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' /etc/apt/apt-mirrors.txt
          sudo apt-get update
      - name: Set up GCC
        run: |
          sudo apt-get install -y gcc-14 g++-14

          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-14 10

          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
      - name: Build pyvrp
        # First, we install the project into the environment. This ensures
        # imports like "from pyvrp import X" work. This builds in release mode
        # by default, but we'd like to have debug symbols for CodSpeed to make
        # sense, so we have to build in debugoptimized mode.
        run: |
          uv sync
          uv run buildtools/build_extensions.py --build_type debugoptimized --clean
      - name: Run benchmarks
        # We evaluate the microbenchmarks using the release build.
        uses: CodSpeedHQ/action@76578c2a7ddd928664caa737f0e962e3085d4e7c # v3.8.1
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest benchmarks/ --codspeed
